# Generated by Django 4.1 on 2022-08-28 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=20, verbose_name="name")),
                (
                    "category_description",
                    models.CharField(max_length=100, verbose_name="description"),
                ),
                (
                    "category_image",
                    models.ImageField(
                        null=True, upload_to="posts/images", verbose_name="image"
                    ),
                ),
                (
                    "category_user",
                    models.ManyToManyField(
                        null=True,
                        related_name="cat_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={"verbose_name_plural": "categories",},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=20, verbose_name="title")),
                (
                    "post_image",
                    models.ImageField(
                        null=True, upload_to="posts/images", verbose_name="image"
                    ),
                ),
                ("post_content", models.TextField(null=True)),
                ("post_created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("post_updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "post_category_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="categories.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "post_tags",
                    models.ManyToManyField(
                        blank=True, null=True, to="categories.tag", verbose_name="tags"
                    ),
                ),
                (
                    "post_user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_content", models.TextField(max_length=200)),
                ("comment_time", models.DateTimeField(auto_now_add=True)),
                (
                    "comment_post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.post",
                    ),
                ),
                (
                    "comment_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
