# Generated by Django 4.1 on 2022-08-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_post_post_like_alter_category_category_user_and_more'),
        ('categories', '0005_post_dislikes'),
    ]

    operations = [
    ]
