# Generated by Django 4.1 on 2022-09-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0007_alter_comment_options_remove_post_post_like_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Tag",),
    ]
