# Generated by Django 4.1 on 2022-09-01 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0008_delete_tag"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="category_user",),
        migrations.AddField(
            model_name="category",
            name="category_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cat_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
